### ISSUE TITLE
Console says "Not allowed to load local resource: "/my/path/igdm/browser/login.html"

### ISSUE THREAD

**Issue by atcasanova** [igdmapps/igdm#1176]
**Bug Description**

Just made a fresh install (git clone + cd igdm && npm install && npm start. IG:dm window opens but it's blank. Console says "Not allowed to load local resource" and points to browser/login.html.

I tried to ``` find . -iname "login.html"``` and there are no hits. Couldn't find it on the repo either.

**Comment by ifedapoolarewaju** [comment]
Could you run ‘gulp build’ and see what happens

**Comment by atcasanova** [comment]
I didn't have gulp installed, so I had to install it (i've been using igdm for some time now, i never had gulp installed though). 
So. I installed it and:
```
$ gulp build
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'for-own'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/liftoff/node_modules/object.map/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Then I tried:
```
$ npm install for-own
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN electron-builder-squirrel-windows@20.29.0 requires a peer of app-builder-lib@~20.29.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ for-own@1.0.0
updated 1 package and audited 8659 packages in 3.382s
found 0 vulnerabilities
```

and gulp build again:
```
$ gulp build
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'for-own'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/liftoff/node_modules/object.map/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Still not working.

**Comment by atcasanova** [comment]
So. I found a package named "node-for-own" and installed it
```sudo apt install node-for-own```
And tried a fresh install again.

Got the same behavior. 
Then I tried ```gulp build``` again

```$ gulp build
[15:17:19] Using gulpfile ~/lab/igdm/gulpfile.js
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
