### ISSUE TITLE
Login code (either from SMS or authy) doesn't authorize login

### ISSUE THREAD

**Issue by FyreDemonyte** [igdmapps/igdm#1200]
![Screenshot from 2020-02-02 22-37-02](https://user-images.githubusercontent.com/18432686/73623938-dc6e7600-460c-11ea-924d-d1f2f64ee0c7.png)

Attempting to enter the login code from Authy or SMS doesn't work.

**Comment by bviktor** [comment]
Same here. It keeps sending me the 2FA code, I keep entering it, but then it's an infinite loop.

**Comment by ANA-Y-N** [comment]
If you intend to access this app through a device other than a mobile phone, you must use your usual password for your mobile phone.i think that is solution

**Comment by bviktor** [comment]
I use the "usual" password (what other passwords do we have?), but it keeps asking for the 2FA code. Which I receive and enter, but then it loads some more, sends a new 2FA code and asks for the code again, and it just goes on and on until I'm locked out of Instagram.

I opened the web browser, where it asks for confirmation if this login attempt was me or not. I click on "this was me", but it still won't let me in. Ever.

**Comment by ANA-Y-N** [comment]
I'm sorry. There is no other way to solve this problem than I understand

‫‪bviktor‬‏ <‪notifications@github.com‬‏> در تاریخ جمعه ۷ فوریهٔ ۲۰۲۰ ساعت
۱۲:۰۲ نوشت:‬

**Comment by FyreDemonyte** [comment]
It's also not showing any login attempt/activity on the https://www.instagram.com/session/login_activity/ page of instagram from this IGdm app. 

However on the https://www.instagram.com/emails/emails_sent/ page it's shown logins by this app from (even so the app never gets passed the security code):
```
New login to Instagram from Instagram on S300
Feb 10, 2020 5:00 AM
Sent to: [my email] · Sent from: security@mail.instagram.com
```
But also another from this same app shown as:
```
New login to Instagram from Instagram on KAZAM THUNDER2 45L
Feb 2, 2020 11:07 AM
Sent to: [my email] · Sent from: security@mail.instagram.com
```

So this app is faking the device name ? or what is going on ?

**Comment by FyreDemonyte** [comment]
@ANA-Y-N The login credentials for mobile and desktop (chrome browser) are the same. Including that you can login using facebook. 

However something else I discovered, is when sign in from desktop (chrome browser) with instagram credentials (not facebook),  it then requests for the 6 digit authentication code, which I receive by a SMS code. **This doesn't happen when trying to login with the IGdm app (even so I have two-factor authentication app (authy) enabled as well for security login).** 

The SMS code only occurs with the IGdm app when the Authy app login method is **disabled** in instagram. **Which in either case isn't working.**

**Comment by ANA-Y-N** [comment]
THANK YOU FOR YOUR ADVICE

‫‪Demon‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۱۰ فوریهٔ ۲۰۲۰ ساعت
۳:۰۲ نوشت:‬

**Comment by FyreDemonyte** [comment]
@ifedapoolarewaju If you have the chance please look into this. Would really like to be able to use this on my linux box (Ubuntu 18.04)

**Comment by MJ94** [comment]
I'm also encountering the same issue. The SMS is entered and I receive another code via SMS or the following error message:

> Uncaught Exception:
Error: Object has been destroyed
    at EventEmitter.electron.ipcMain.on (/Applications/IGdm.app/Contents/Resources/app.asar/main/main.js:109:20)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/IGdm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

**Comment by FyreDemonyte** [comment]
Any progress on this?

I've also checked to see what connections this app is making during the login/code verification process:
![Screenshot from 2020-03-05 21-40-51](https://user-images.githubusercontent.com/18432686/76045055-17283e80-5f2a-11ea-981e-c1a30c2ec492.png)

All connection attempts are to instagram's server. However, the app is still failing to either login properly, or is not loading after it logs in. As I'm receiving an email notification that a new login has occurred from a device not usually used: 
![Screenshot from 2020-03-05 21-44-33](https://user-images.githubusercontent.com/18432686/76045263-8736c480-5f2a-11ea-8c6a-88c700901873.png)

@ANA-Y-N is there a way to see any debug info ? Please assist so we can get this app working thank you

**Comment by FyreDemonyte** [comment]
Also upon startup of the app it makes two connections:

![Screenshot from 2020-03-05 22-16-42](https://user-images.githubusercontent.com/18432686/76046866-1c3bbc80-5f2f-11ea-926a-67996d60f6ce.png)

What are these for ?

**Comment by bviktor** [comment]
I switched to the Windows Store app which now has DMs, never looked back lol.

**Comment by FyreDemonyte** [comment]
@bviktor nice, but useless for me, will just use the mobile app for now, until hopefully they update this one or until a Linux compatible app is released. @ifedapoolarewaju but in either case I'm hoping this app isn't stealing login credentials since it's not working as intended :-1:

**Comment by ifedapoolarewaju** [comment]
> hoping this app isn't stealing login credentials since it's not working as intended

@FyreDemonyte the app certainly isn't stealing user credentials. It'll be a bad move to steal people's credentials and still publish the code on github.

> So this app is faking the device name

☝️ This is actually what is happening. The app has to present itself as a mobile device to be able to communicate with Instagram's API.

The Login code verification not working however is an issue that does need fixing. It is an issue related 2FA login. Users without 2FA are able to login fine. I'm hoping to find some time to fix this soon.

**Comment by FyreDemonyte** [comment]
@ifedapoolarewaju thank you, I will await the next update :100:

**Comment by FyreDemonyte** [comment]
Confirming that upon disabling 2 Factor authentication, the app was able to login. However this is extremely not an advisable way to use any social platform. Hopefully this will be remedied asap. :rocket:

**Comment by FyreDemonyte** [comment]
Any update on fixing the 2FA login issue ?
