### ISSUE TITLE
Uncaught Exception:

### ISSUE THREAD

**Issue by kimmypoohx3** [igdmapps/igdm#1298]
TypeError: Cannot read property 'webContents' of null
    at MacUpdater.autoUpdater.on (/Volumes/IGdm 2.6.5/IGdm.app/Contents/Resources/app.asar/main/autoupdater.js:33:9)
    at emitOne (events.js:116:13)
    at MacUpdater.emit (events.js:211:7)
    at ProgressCallbackTransform.downloadOptions.onProgress.it [as onProgress] (/Volumes/IGdm 2.6.5/IGdm.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:549:47)
    at ProgressCallbackTransform._transform (/Volumes/IGdm 2.6.5/IGdm.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/ProgressCallbackTransform.ts:36:12)
    at ProgressCallbackTransform.Transform._read (_stream_transform.js:186:10)
    at ProgressCallbackTransform.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at ProgressCallbackTransform.Writable.write (_stream_writable.js:290:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at IncomingMessage._pushInternalData (/Volumes/IGdm 2.6.5/IGdm.app/Contents/Resources/electron.asar/browser/api/net.js:74:30)
    at URLRequest.IncomingMessage.urlRequest.on (/Volumes/IGdm 2.6.5/IGdm.app/Contents/Resources/electron.asar/browser/api/net.js:27:12)
    at emitTwo (events.js:126:13)
    at URLRequest.emit (events.js:214:7)

**Comment by ifedapoolarewaju** [comment]
Hi there, please download the latest version from the website https://igdm.me
