### ISSUE TITLE
auto update failed all the time, downloaded latest version, still auto update and still failed

### ISSUE THREAD

**Issue by amylucia** [igdmapps/igdm#1300]
hi, please help fix update issue.
auto update failed all the time, downloaded latest version, still auto update and still failed
![image](https://user-images.githubusercontent.com/44507232/80916314-eac05100-8d25-11ea-9e82-cf4a814bea07.png)

**Comment by FyreDemonyte** [comment]
Update is failing with:

```python
demon@Bionic18:~$ igdm
Checking for update
Found version 3.0.1 (url: IGdm-3.0.1-x86_64.AppImage)
Downloading update from IGdm-3.0.1-x86_64.AppImage
updaterCacheDirName is not specified in app-update.yml Was app build using at least electron-builder 20.34.0?
No cached update info available
Error: Error: APPIMAGE env is not defined
    at newError (/opt/IGdm/resources/app.asar/node_modules/builder-util-runtime/src/index.ts:29:17)
    at Object.<anonymous> (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:47:17)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:44:11)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:608:25
From previous event:
    at AppImageUpdater.executeDownload (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:539:68)
    at AppImageUpdater.executeDownload (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:27:18)
    at AppImageUpdater.doDownloadUpdate (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:40:17)
    at AppImageUpdater.downloadUpdate (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:414:19)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:377:49
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:356:34)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:284:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:279:33)
    at AppImageUpdater.checkForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:218:35)
    at Object.exports.init (/opt/IGdm/resources/app.asar/main/autoupdater.js:37:15)
    at App.app.on (/opt/IGdm/resources/app.asar/main/main.js:148:15)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
Unhandled rejection Error: APPIMAGE env is not defined
    at newError (/opt/IGdm/resources/app.asar/node_modules/builder-util-runtime/src/index.ts:29:17)
    at Object.<anonymous> (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:47:17)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:44:11)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:608:25
From previous event:
    at AppImageUpdater.executeDownload (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:539:68)
    at AppImageUpdater.executeDownload (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:27:18)
    at AppImageUpdater.doDownloadUpdate (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:40:17)
    at AppImageUpdater.downloadUpdate (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:414:19)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:377:49
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:356:34)
    at /opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:284:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:279:33)
    at AppImageUpdater.checkForUpdates (/opt/IGdm/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:218:35)
    at Object.exports.init (/opt/IGdm/resources/app.asar/main/autoupdater.js:37:15)
    at App.app.on (/opt/IGdm/resources/app.asar/main/main.js:148:15)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
```

**Comment by billxsand** [comment]
Still having this issue, it wouldn't be such a problem if the Autoupdate window didn't pop up every time!
